### ISSUE TITLE
isPublicHoliday bude vždy true

### ISSUE THREAD

**Issue by faileon** [vaniocz/svatky-vanio-cz#1]
https://github.com/vaniocz/svatky-vanio-cz/blob/06f70a8c2f0b901586945ebdceb501c3495b4085/api/index.php#L149

díky změne v posledním [commitu ](https://github.com/vaniocz/svatky-vanio-cz/commit/06f70a8c2f0b901586945ebdceb501c3495b4085#diff-3f17f7cb0633b52a6e01ad101d2a5655R103)

**Comment by stanleyk** [comment]
Super, díky moc, opraveno.
