### ISSUE TITLE
Chybný začátek dne?

### ISSUE THREAD

**Issue by risa2000** [vaniocz/svatky-vanio-cz#6]
Když pošlu dotaz po půlnoci, bez zadání data, t.j. zavolám:
```
https://svatky.vanio.cz/api/
```
tak, teď, ve středu, 15. 9. 2021, v 0:37, mi to vrátí:
```python
{'date': '2021-09-14',
 'month': {'nominative': 'září', 'genitive': 'září'},
 'dow': 'úterý',
 'name': 'Radka',
 'isPublicHoliday': False}
```

**Comment by stanleyk** [comment]
V kontejneru byla default timezona UTC. Opraveno, vystaveno. Díky za report!
